#!/bin/zsh

for seed in {0,1,2,3,4}; do
    for weight in {0.00001,1}; do
        ~/Documents/Code/Tensorflow/env/bin/python model.py 32 -l 32 -n "l32b w$weight s$seed i0" -s $seed -p 30 -w $weight
    done
done
